title: Webscript, an HTML replacement for Javascript-based web applications
description: Webscript is an HTML-like Javascript syntax for defining, creating, composing and manipulating DOM elements.
theme: jekyll-theme-minimal